### ISSUE TITLE
Give possibility to edit the values in the form after a plugin is added

### ISSUE THREAD

**Issue by TorMec** [dokufreaks/dokuwiki-translation#80] opened 2015-07-30 07:42 UTC
There is no way to correct/edit a wrong/changed value after a Plugin is sent. 

For instance, if I submit a wrong Git url, the plugin will be added in the list at translate.dokuwiki.org, but than I have no chance to correct the mistake.

In my case I've submitted a wrong url for PyCode Plugin and now I can't correct it.

**Comment by Klap-in** [comment] 2015-07-30 09:40
That is useful indeed. 
An duplicate of this issue is available at #19

**Closed by Klap-in** 2015-07-30 09:40 UTC
