### ISSUE TITLE
Many errors sent by eMail

### ISSUE THREAD

**Issue by gamma** [dokufreaks/dokuwiki-translation#110] opened 2023-03-28 06:21 UTC
Hi, for several days now I receive a lot of error emails from the tool. 

For example:

```
Hello,

the automatic update of your Site Export Plugin failed.
I wasn't able to pull from the given repository.
Please ensure that the given URL is publicly accessible.

The git URL was https://github.com/i-net-software/dokuwiki-plugin-siteexport.git

Regards,
DokuWiki Translation Tool
/
```

AFAIK there are no changes in my repositories that would trigger that error. I think there was a comment on the DW mailing list some weeks ago about the same issue. Please investigate 👍

**Comment by splitbrain** [comment] 2023-03-28 07:18
See https://github.com/dokufreaks/dokuwiki-translation/issues/86#issuecomment-1485250777

The issue was caused by Github changing their SSH key. I thought I had fixed the problem on our side but apparently not. Gotta figure out what's missing

**Comment by Klap-in** [comment] 2023-06-24 21:38
Close as duplicate of #86 and #56

**Closed by Klap-in** 2023-06-24 21:38 UTC
